"""initial migration

Revision ID: 3f9316e9e523
Revises: 
Create Date: 2022-06-08 21:33:03.840274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9316e9e523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencypair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker1', sa.String(length=3), nullable=True),
    sa.Column('ticker2', sa.String(length=3), nullable=True),
    sa.CheckConstraint('char_length(ticker1) = 3'),
    sa.CheckConstraint('char_length(ticker2) = 3'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker1', 'ticker2')
    )
    op.create_index(op.f('ix_currencypair_id'), 'currencypair', ['id'], unique=False)
    op.create_index(op.f('ix_currencypair_ticker1'), 'currencypair', ['ticker1'], unique=False)
    op.create_index(op.f('ix_currencypair_ticker2'), 'currencypair', ['ticker2'], unique=False)
    op.create_table('exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencypair_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Numeric(scale=4), nullable=True),
    sa.ForeignKeyConstraint(['currencypair_id'], ['currencypair.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'currencypair_id')
    )
    op.create_index(op.f('ix_exchangerate_date'), 'exchangerate', ['date'], unique=False)
    op.create_index(op.f('ix_exchangerate_id'), 'exchangerate', ['id'], unique=False)
    op.create_index(op.f('ix_exchangerate_rate'), 'exchangerate', ['rate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchangerate_rate'), table_name='exchangerate')
    op.drop_index(op.f('ix_exchangerate_id'), table_name='exchangerate')
    op.drop_index(op.f('ix_exchangerate_date'), table_name='exchangerate')
    op.drop_table('exchangerate')
    op.drop_index(op.f('ix_currencypair_ticker2'), table_name='currencypair')
    op.drop_index(op.f('ix_currencypair_ticker1'), table_name='currencypair')
    op.drop_index(op.f('ix_currencypair_id'), table_name='currencypair')
    op.drop_table('currencypair')
    # ### end Alembic commands ###
